### ISSUE TITLE
Status :The following error occurred when installing the plugin: Error

### ISSUE THREAD

**Issue by sirtobey** [Saiyato/volumio-snapcast-plugin#40]
Hello Saiyato

Thank you very much for providing this plugin - it saves me a lot of work.

However, I ran into some trouble when trying to install it.
```
Svolumio@VolumioMain:~/volumio-snapcast-plugin$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error
```

I am running the latest version of Volumio on a RaspberryPi 3 Type B.
I am uncertain if there is enough space on the SD card, but I ran df -h and doesn't look bad:
```
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mmcblk0p2                    2.2G  618M  1.5G  30% /imgpart
/dev/loop0                        273M  273M     0 100% /static
overlay                           4.8G   63M  4.5G   2% /
devtmpfs                          478M     0  478M   0% /dev
tmpfs                             489M     0  489M   0% /dev/shm
tmpfs                             489M  4.7M  484M   1% /run
tmpfs                             5.0M  4.0K  5.0M   1% /run/lock
tmpfs                             489M     0  489M   0% /sys/fs/cgroup
tmpfs                             489M   28K  489M   1% /tmp
tmpfs                              20M   68K   20M   1% /var/log
tmpfs                             489M     0  489M   0% /var/spool/cups
tmpfs                             489M     0  489M   0% /var/spool/cups/tmp
/dev/mmcblk0p1                     61M   35M   26M  58% /boot
//xx.xx.xx.xx/Multimedia/music  3.5T  3.2T  318G  92% /mnt/NAS/Name
tmpfs                              98M     0   98M   0% /run/user/1000
```

Do you perhaps know what could be the issue, or if I can find more useful information than "Error"? :D

**Comment by sirtobey** [comment]
BTW: I just tried the same with my Raspi2 and another SD card - same result, it stops when trying to install dependencies.

**Comment by Saiyato** [comment]
Did you remove the zip first?

**Comment by sirtobey** [comment]
Yes, I did on both my devices.

**Comment by sirtobey** [comment]
I haven't tried the lazy installation though. Might try it later today.

**Comment by Saiyato** [comment]
Just committed that one, but I found that `volumio plugin install` doesn't work for me... ever... in build 368 :(

So we're definitely not there yet

**Comment by sirtobey** [comment]
Let me know how I can help :)

**Comment by Saiyato** [comment]
I'm not sure... the problem is both the script and manual installation of the plugin fails:

```
volumio@volumioboss:~$ cd volumio-snapcast-plugin/
volumio@volumioboss:~/volumio-snapcast-plugin$ ls -al
total 260
drwxr-xr-x 10 root    root      4096 Mar 11 18:03 .
drwxr-xr-x  1 volumio volumio   4096 Mar 11 16:36 ..
drwxr-xr-x  8 root    root      4096 Mar 11 16:38 .git
-rw-r--r--  1 root    root       378 Mar 11 16:38 .gitattributes
-rw-r--r--  1 root    root     11930 Mar 11 16:38 README.md
-rw-r--r--  1 root    root     14405 Mar 11 16:38 UIConfig.json
-rw-r--r--  1 root    root      3665 Mar 11 16:38 brainstorm.txt
-rw-r--r--  1 root    root      2416 Mar 11 16:38 config.json
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 examples
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 i18n
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 images
-rw-r--r--  1 root    root     41212 Mar 11 16:38 index.js
-rw-r--r--  1 root    root      3669 Mar 11 16:38 install.sh
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 known_working_versions
drwxr-xr-x 44 root    root      4096 Mar 11 16:38 node_modules
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 options
-rw-r--r--  1 root    root      1919 Mar 11 16:38 package.json
-rw-r--r--  1 root    root    119996 Mar 11 16:38 snapcast.pptx
-rw-r--r--  1 root    root       427 Mar 11 16:38 spotififo.service
drwxr-xr-x  2 root    root      4096 Mar 11 16:38 templates
-rw-r--r--  1 root    root      1418 Mar 11 16:38 uninstall.sh
volumio@volumioboss:~/volumio-snapcast-plugin$ sudo volumio plugin install
[sudo] password for volumio:

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
```

I never managed to get past this point.

**Comment by Saiyato** [comment]
I just updated the readme, run the installer script without sudo and it works..

```
volumio@volumioboss:~$ sh volumio_installer.sh
Cloning github repo... (this might take a while)
Cloning into '/home/volumio/volumio-snapcast-plugin'...
remote: Counting objects: 1013, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1013 (delta 10), reused 11 (delta 4), pack-reused 992
Receiving objects: 100% (1013/1013), 16.89 MiB | 250.00 KiB/s, done.
Resolving deltas: 100% (414/414), done.
Checking connectivity... done.
Cleaning up the directory...
rm: cannot remove 'readme.md': No such file or directory
Installing plugin...

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 90
Status :Adding plugin to registry
Progress: 100
Status :Plugin Successfully Installed
Done!
Done!
```

**Comment by sirtobey** [comment]
Thanks!

However, I didn't run the manual plug-in installation as root, I ran it as volumio user. I'll have to check later if I can run the script.

I suspect this might be related to a recent change npm made when running `npm install` as root user..

**Comment by Saiyato** [comment]
The previous version of the script didn't clean up the directory, which made it super bloated and caused it to fail to install every time. That's why the latest version should work fine.

**Comment by sirtobey** [comment]
I see :)
I'll try it out later today or tomorrow. Thank you very much!

**Comment by sirtobey** [comment]
Damn, I still get the same error when trying to install it with both ways to execute the script. Both will again fail when installing dependencies, with only the error: "Error"..

**Comment by Saiyato** [comment]
I'm going to need more logging to identify your problem. What did you do exactly? Step-by-step please.
I've installed multiple plugins using the new scripts I wrote today, all succeeded, so it must be something local imho.

**Comment by Saiyato** [comment]
Have you tried:

`
sudo wget -O volumio_install_from_zip.sh https://raw.githubusercontent.com/Saiyato/volumio-plugin-helper/master/volumio_install_from_zip.sh
`

and

`
sh volumio_install_from_zip.sh Saiyato volumio-snapcast-plugin
`

You can't make any errors anymore, since it's all scripted.

**Comment by sirtobey** [comment]
see below, didn't know email does not support markdown

**Comment by sirtobey** [comment]
Hi

I tried both installer versions, the one with volumio_install_from_zip, and the one where I clone the repo and launch the script itself.
I should note, that it's on the same installation as I tried the manual installation before. The error is the same, there is a bit more log though:


```
volumio@VolumioBuero:~$ sh volumio_install_from_zip.sh Saiyato volumio-snapcast-plugin
mkdir: cannot create directory '/home/volumio/volumio-snapcast-plugin': File exists
Downloading and extracting zip file...
converted 'https://github.com/Saiyato/volumio-snapcast-plugin/raw/master/volumio-snapcast-plugin.zip' (ANSI_X3.4-1968) -> 'https://github.com/Saiyato/volumio-snapcast-plugin/raw/master/volumio-snapcast-plugin.zip' (UTF-8)
--2018-03-12 21:49:32-- https://github.com/Saiyato/volumio-snapcast-plugin/raw/master/volumio-snapcast-plugin.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Saiyato/volumio-snapcast-plugin/master/volumio-snapcast-plugin.zip [following]
converted 'https://raw.githubusercontent.com/Saiyato/volumio-snapcast-plugin/master/volumio-snapcast-plugin.zip' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/Saiyato/volumio-snapcast-plugin/master/volumio-snapcast-plugin.zip' (UTF-8)
--2018-03-12 21:49:32-- https://raw.githubusercontent.com/Saiyato/volumio-snapcast-plugin/master/volumio-snapcast-plugin.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 550278 (537K) [application/zip]
Saving to: 'volumio-snapcast-plugin.zip'

volumio-snapcast-pl 100%[=====================>] 537.38K --.-KB/s in 0.09s

2018-03-12 21:49:33 (5.70 MB/s) - 'volumio-snapcast-plugin.zip' saved [550278/550278]

MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html

volumio-snapcast-plugin.zip opened
extracting: install.sh
extracting: package.json
extracting: spotififo.service
extracting: UIConfig.json
extracting: uninstall.sh
creating directory: i18n/
extracting: i18n/strings_en.json
creating directory: node_modules/
creating directory: node_modules/after/
extracting: node_modules/after/.npmignore
extracting: node_modules/after/.travis.yml
extracting: node_modules/after/index.js
extracting: node_modules/after/LICENCE
extracting: node_modules/after/package.json
extracting: node_modules/after/README.md
creating directory: node_modules/after/test/
extracting: node_modules/after/test/after-test.js
creating directory: node_modules/backo2/
extracting: node_modules/backo2/.npmignore
extracting: node_modules/backo2/component.json
extracting: node_modules/backo2/History.md
extracting: node_modules/backo2/index.js
extracting: node_modules/backo2/Makefile
extracting: node_modules/backo2/package.json
extracting: node_modules/backo2/Readme.md
creating directory: node_modules/backo2/test/
extracting: node_modules/backo2/test/index.js
creating directory: node_modules/balanced-match/
extracting: node_modules/balanced-match/.npmignore
extracting: node_modules/balanced-match/index.js
extracting: node_modules/balanced-match/LICENSE.md
extracting: node_modules/balanced-match/package.json
extracting: node_modules/balanced-match/README.md
creating directory: node_modules/brace-expansion/
extracting: node_modules/brace-expansion/index.js
extracting: node_modules/brace-expansion/package.json
extracting: node_modules/brace-expansion/README.md
creating directory: node_modules/component-bind/
extracting: node_modules/component-bind/.npmignore
extracting: node_modules/component-bind/component.json
extracting: node_modules/component-bind/History.md
extracting: node_modules/component-bind/index.js
extracting: node_modules/component-bind/Makefile
extracting: node_modules/component-bind/package.json
extracting: node_modules/component-bind/Readme.md
creating directory: node_modules/component-emitter/
extracting: node_modules/component-emitter/.npmignore
extracting: node_modules/component-emitter/.travis.yml
extracting: node_modules/component-emitter/bower.json
extracting: node_modules/component-emitter/component.json
extracting: node_modules/component-emitter/History.md
extracting: node_modules/component-emitter/index.js
extracting: node_modules/component-emitter/Makefile
extracting: node_modules/component-emitter/package.json
extracting: node_modules/component-emitter/Readme.md
creating directory: node_modules/component-inherit/
extracting: node_modules/component-inherit/.npmignore
extracting: node_modules/component-inherit/component.json
extracting: node_modules/component-inherit/History.md
extracting: node_modules/component-inherit/index.js
extracting: node_modules/component-inherit/Makefile
extracting: node_modules/component-inherit/package.json
extracting: node_modules/component-inherit/Readme.md
creating directory: node_modules/component-inherit/test/
extracting: node_modules/component-inherit/test/inherit.js
creating directory: node_modules/concat-map/
extracting: node_modules/concat-map/.travis.yml
creating directory: node_modules/concat-map/example/
extracting: node_modules/concat-map/example/map.js
extracting: node_modules/concat-map/index.js
extracting: node_modules/concat-map/LICENSE
extracting: node_modules/concat-map/package.json
extracting: node_modules/concat-map/README.markdown
creating directory: node_modules/concat-map/test/
extracting: node_modules/concat-map/test/map.js
creating directory: node_modules/debug/
extracting: node_modules/debug/.coveralls.yml
extracting: node_modules/debug/.eslintrc
extracting: node_modules/debug/.jshintrc
extracting: node_modules/debug/.npmignore
extracting: node_modules/debug/.travis.yml
extracting: node_modules/debug/bower.json
extracting: node_modules/debug/browser.js
extracting: node_modules/debug/CHANGELOG.md
extracting: node_modules/debug/component.json
extracting: node_modules/debug/debug.js
extracting: node_modules/debug/History.md
extracting: node_modules/debug/karma.conf.js
extracting: node_modules/debug/LICENSE
extracting: node_modules/debug/Makefile
extracting: node_modules/debug/node.js
extracting: node_modules/debug/package.json
extracting: node_modules/debug/Readme.md
creating directory: node_modules/debug/src/
extracting: node_modules/debug/src/browser.js
extracting: node_modules/debug/src/debug.js
extracting: node_modules/debug/src/index.js
extracting: node_modules/debug/src/node.js
creating directory: node_modules/engine.io-client/
extracting: node_modules/engine.io-client/.npmignore
extracting: node_modules/engine.io-client/.travis.yml
extracting: node_modules/engine.io-client/.zuul.yml
extracting: node_modules/engine.io-client/engine.io.js
extracting: node_modules/engine.io-client/History.md
extracting: node_modules/engine.io-client/index.js
creating directory: node_modules/engine.io-client/lib/
extracting: node_modules/engine.io-client/lib/index.js
extracting: node_modules/engine.io-client/lib/socket.js
extracting: node_modules/engine.io-client/lib/transport.js
creating directory: node_modules/engine.io-client/lib/transports/
extracting: node_modules/engine.io-client/lib/transports/index.js
extracting: node_modules/engine.io-client/lib/transports/polling-jsonp.js
extracting: node_modules/engine.io-client/lib/transports/polling-xhr.js
extracting: node_modules/engine.io-client/lib/transports/polling.js
extracting: node_modules/engine.io-client/lib/transports/websocket.js
extracting: node_modules/engine.io-client/lib/xmlhttprequest.js
extracting: node_modules/engine.io-client/LICENSE
extracting: node_modules/engine.io-client/Makefile
creating directory: node_modules/engine.io-client/node_modules/
creating directory: node_modules/engine.io-client/node_modules/ws/
extracting: node_modules/engine.io-client/node_modules/ws/.npmignore
extracting: node_modules/engine.io-client/node_modules/ws/.travis.yml
extracting: node_modules/engine.io-client/node_modules/ws/index.js
creating directory: node_modules/engine.io-client/node_modules/ws/lib/
extracting: node_modules/engine.io-client/node_modules/ws/lib/BufferPool.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/BufferUtil.fallback.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/BufferUtil.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/ErrorCodes.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Extensions.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/PerMessageDeflate.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Receiver.hixie.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Receiver.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Sender.hixie.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Sender.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Validation.fallback.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/Validation.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js
extracting: node_modules/engine.io-client/node_modules/ws/lib/WebSocketServer.js
extracting: node_modules/engine.io-client/node_modules/ws/Makefile
extracting: node_modules/engine.io-client/node_modules/ws/package.json
extracting: node_modules/engine.io-client/node_modules/ws/README.md
extracting: node_modules/engine.io-client/package.json
extracting: node_modules/engine.io-client/README.md
creating directory: node_modules/engine.io-parser/
extracting: node_modules/engine.io-parser/.npmignore
extracting: node_modules/engine.io-parser/.travis.yml
extracting: node_modules/engine.io-parser/.zuul.yml
extracting: node_modules/engine.io-parser/History.md
extracting: node_modules/engine.io-parser/index.js
creating directory: node_modules/engine.io-parser/lib/
extracting: node_modules/engine.io-parser/lib/browser.js
extracting: node_modules/engine.io-parser/lib/index.js
extracting: node_modules/engine.io-parser/lib/keys.js
extracting: node_modules/engine.io-parser/LICENSE
extracting: node_modules/engine.io-parser/Makefile
creating directory: node_modules/engine.io-parser/node_modules/
creating directory: node_modules/engine.io-parser/node_modules/has-binary/
extracting: node_modules/engine.io-parser/node_modules/has-binary/.npmignore
creating directory: node_modules/engine.io-parser/node_modules/has-binary/fixtures/
extracting: node_modules/engine.io-parser/node_modules/has-binary/fixtures/big.json
extracting: node_modules/engine.io-parser/node_modules/has-binary/History.md
extracting: node_modules/engine.io-parser/node_modules/has-binary/index.js
extracting: node_modules/engine.io-parser/node_modules/has-binary/LICENSE
extracting: node_modules/engine.io-parser/node_modules/has-binary/Makefile
extracting: node_modules/engine.io-parser/node_modules/has-binary/package.json
extracting: node_modules/engine.io-parser/node_modules/has-binary/README.md
extracting: node_modules/engine.io-parser/node_modules/has-binary/test.js
extracting: node_modules/engine.io-parser/package.json
extracting: node_modules/engine.io-parser/Readme.md
creating directory: node_modules/fs-extra/
extracting: node_modules/fs-extra/.npmignore
extracting: node_modules/fs-extra/CHANGELOG.md
creating directory: node_modules/fs-extra/lib/
creating directory: node_modules/fs-extra/lib/copy/
extracting: node_modules/fs-extra/lib/copy/copy.js
extracting: node_modules/fs-extra/lib/copy/index.js
extracting: node_modules/fs-extra/lib/copy/ncp.js
creating directory: node_modules/fs-extra/lib/copy-sync/
extracting: node_modules/fs-extra/lib/copy-sync/copy-file-sync.js
extracting: node_modules/fs-extra/lib/copy-sync/copy-sync.js
extracting: node_modules/fs-extra/lib/copy-sync/index.js
creating directory: node_modules/fs-extra/lib/empty/
extracting: node_modules/fs-extra/lib/empty/index.js
creating directory: node_modules/fs-extra/lib/ensure/
extracting: node_modules/fs-extra/lib/ensure/file.js
extracting: node_modules/fs-extra/lib/ensure/index.js
extracting: node_modules/fs-extra/lib/ensure/link.js
extracting: node_modules/fs-extra/lib/ensure/symlink-paths.js
extracting: node_modules/fs-extra/lib/ensure/symlink-type.js
extracting: node_modules/fs-extra/lib/ensure/symlink.js
extracting: node_modules/fs-extra/lib/index.js
creating directory: node_modules/fs-extra/lib/json/
extracting: node_modules/fs-extra/lib/json/index.js
extracting: node_modules/fs-extra/lib/json/jsonfile.js
extracting: node_modules/fs-extra/lib/json/output-json-sync.js
extracting: node_modules/fs-extra/lib/json/output-json.js
creating directory: node_modules/fs-extra/lib/mkdirs/
extracting: node_modules/fs-extra/lib/mkdirs/index.js
extracting: node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js
extracting: node_modules/fs-extra/lib/mkdirs/mkdirs.js
extracting: node_modules/fs-extra/lib/mkdirs/win32.js
creating directory: node_modules/fs-extra/lib/move/
extracting: node_modules/fs-extra/lib/move/index.js
creating directory: node_modules/fs-extra/lib/output/
extracting: node_modules/fs-extra/lib/output/index.js
creating directory: node_modules/fs-extra/lib/remove/
extracting: node_modules/fs-extra/lib/remove/index.js
creating directory: node_modules/fs-extra/lib/util/
extracting: node_modules/fs-extra/lib/util/assign.js
extracting: node_modules/fs-extra/lib/util/utimes.js
creating directory: node_modules/fs-extra/lib/walk/
extracting: node_modules/fs-extra/lib/walk/index.js
extracting: node_modules/fs-extra/LICENSE
extracting: node_modules/fs-extra/package.json
extracting: node_modules/fs-extra/README.md
creating directory: node_modules/fs.realpath/
extracting: node_modules/fs.realpath/index.js
extracting: node_modules/fs.realpath/LICENSE
extracting: node_modules/fs.realpath/old.js
extracting: node_modules/fs.realpath/package.json
extracting: node_modules/fs.realpath/README.md
creating directory: node_modules/glob/
extracting: node_modules/glob/changelog.md
extracting: node_modules/glob/common.js
extracting: node_modules/glob/glob.js
extracting: node_modules/glob/LICENSE
extracting: node_modules/glob/package.json
extracting: node_modules/glob/README.md
extracting: node_modules/glob/sync.js
creating directory: node_modules/graceful-fs/
extracting: node_modules/graceful-fs/fs.js
extracting: node_modules/graceful-fs/graceful-fs.js
extracting: node_modules/graceful-fs/legacy-streams.js
extracting: node_modules/graceful-fs/LICENSE
extracting: node_modules/graceful-fs/package.json
extracting: node_modules/graceful-fs/polyfills.js
extracting: node_modules/graceful-fs/README.md
creating directory: node_modules/has-binary/
extracting: node_modules/has-binary/.npmignore
extracting: node_modules/has-binary/History.md
extracting: node_modules/has-binary/index.js
extracting: node_modules/has-binary/LICENSE
extracting: node_modules/has-binary/Makefile
extracting: node_modules/has-binary/package.json
extracting: node_modules/has-binary/README.md
extracting: node_modules/has-binary/test.js
creating directory: node_modules/indexof/
extracting: node_modules/indexof/.npmignore
extracting: node_modules/indexof/component.json
extracting: node_modules/indexof/index.js
extracting: node_modules/indexof/Makefile
extracting: node_modules/indexof/package.json
extracting: node_modules/indexof/Readme.md
creating directory: node_modules/inflight/
extracting: node_modules/inflight/inflight.js
extracting: node_modules/inflight/LICENSE
extracting: node_modules/inflight/package.json
extracting: node_modules/inflight/README.md
creating directory: node_modules/inherits/
extracting: node_modules/inherits/inherits.js
extracting: node_modules/inherits/inherits_browser.js
extracting: node_modules/inherits/LICENSE
extracting: node_modules/inherits/package.json
extracting: node_modules/inherits/README.md
creating directory: node_modules/isarray/
creating directory: node_modules/isarray/build/
extracting: node_modules/isarray/build/build.js
extracting: node_modules/isarray/component.json
extracting: node_modules/isarray/index.js
extracting: node_modules/isarray/package.json
extracting: node_modules/isarray/README.md
creating directory: node_modules/json-socket/
extracting: node_modules/json-socket/.npmignore
extracting: node_modules/json-socket/.travis.yml
creating directory: node_modules/json-socket/examples/
extracting: node_modules/json-socket/examples/tcp-example.js
extracting: node_modules/json-socket/examples/unix-socket.js
creating directory: node_modules/json-socket/lib/
extracting: node_modules/json-socket/lib/json-socket.js
extracting: node_modules/json-socket/LICENSE
extracting: node_modules/json-socket/package.json
extracting: node_modules/json-socket/README.md
creating directory: node_modules/jsonfile/
extracting: node_modules/jsonfile/.npmignore
extracting: node_modules/jsonfile/appveyor.yml
extracting: node_modules/jsonfile/CHANGELOG.md
extracting: node_modules/jsonfile/index.js
extracting: node_modules/jsonfile/LICENSE
extracting: node_modules/jsonfile/package.json
extracting: node_modules/jsonfile/README.md
creating directory: node_modules/kew/
extracting: node_modules/kew/.npmignore
extracting: node_modules/kew/.travis.yml
extracting: node_modules/kew/kew.js
extracting: node_modules/kew/LICENSE.TXT
extracting: node_modules/kew/package.json
extracting: node_modules/kew/README.md
creating directory: node_modules/kew/test/
extracting: node_modules/kew/test/chain.js
extracting: node_modules/kew/test/closure_test.js
extracting: node_modules/kew/test/context.js
extracting: node_modules/kew/test/defer.js
extracting: node_modules/kew/test/externs_node.js
extracting: node_modules/kew/test/later.js
extracting: node_modules/kew/test/scopes.js
extracting: node_modules/kew/test/spread.js
extracting: node_modules/kew/test/static.js
creating directory: node_modules/klaw/
extracting: node_modules/klaw/.npmignore
extracting: node_modules/klaw/CHANGELOG.md
extracting: node_modules/klaw/LICENSE
extracting: node_modules/klaw/package.json
extracting: node_modules/klaw/README.md
creating directory: node_modules/klaw/src/
extracting: node_modules/klaw/src/assign.js
extracting: node_modules/klaw/src/index.js
creating directory: node_modules/minimatch/
extracting: node_modules/minimatch/LICENSE
extracting: node_modules/minimatch/minimatch.js
extracting: node_modules/minimatch/package.json
extracting: node_modules/minimatch/README.md
creating directory: node_modules/ms/
extracting: node_modules/ms/.npmignore
extracting: node_modules/ms/History.md
extracting: node_modules/ms/index.js
extracting: node_modules/ms/LICENSE
extracting: node_modules/ms/license.md
extracting: node_modules/ms/package.json
extracting: node_modules/ms/README.md
creating directory: node_modules/multimap/
extracting: node_modules/multimap/.jshintrc
extracting: node_modules/multimap/.npmignore
extracting: node_modules/multimap/.travis.yml
extracting: node_modules/multimap/index.js
extracting: node_modules/multimap/package.json
extracting: node_modules/multimap/README.md
creating directory: node_modules/multimap/test/
extracting: node_modules/multimap/test/es6map.js
extracting: node_modules/multimap/test/index.js
extracting: node_modules/multimap/test/test.html
creating directory: node_modules/net/
extracting: node_modules/net/index.js
extracting: node_modules/net/LICENSE
extracting: node_modules/net/package.json
extracting: node_modules/net/README.md
extracting: node_modules/net/test.js
creating directory: node_modules/once/
extracting: node_modules/once/LICENSE
extracting: node_modules/once/once.js
extracting: node_modules/once/package.json
extracting: node_modules/once/README.md
creating directory: node_modules/parsejson/
extracting: node_modules/parsejson/index.js
extracting: node_modules/parsejson/Makefile
extracting: node_modules/parsejson/package.json
extracting: node_modules/parsejson/test.js
creating directory: node_modules/parseqs/
extracting: node_modules/parseqs/index.js
extracting: node_modules/parseqs/Makefile
extracting: node_modules/parseqs/package.json
extracting: node_modules/parseqs/test.js
creating directory: node_modules/parseuri/
extracting: node_modules/parseuri/History.md
extracting: node_modules/parseuri/index.js
extracting: node_modules/parseuri/Makefile
extracting: node_modules/parseuri/package.json
extracting: node_modules/parseuri/test.js
creating directory: node_modules/path-is-absolute/
extracting: node_modules/path-is-absolute/index.js
extracting: node_modules/path-is-absolute/license
extracting: node_modules/path-is-absolute/package.json
extracting: node_modules/path-is-absolute/readme.md
creating directory: node_modules/rimraf/
extracting: node_modules/rimraf/bin.js
extracting: node_modules/rimraf/LICENSE
extracting: node_modules/rimraf/package.json
extracting: node_modules/rimraf/README.md
extracting: node_modules/rimraf/rimraf.js
creating directory: node_modules/socket.io-client/
extracting: node_modules/socket.io-client/History.md
creating directory: node_modules/socket.io-client/lib/
extracting: node_modules/socket.io-client/lib/index.js
extracting: node_modules/socket.io-client/lib/manager.js
extracting: node_modules/socket.io-client/lib/on.js
extracting: node_modules/socket.io-client/lib/socket.js
extracting: node_modules/socket.io-client/lib/url.js
extracting: node_modules/socket.io-client/LICENSE
creating directory: node_modules/socket.io-client/node_modules/
creating directory: node_modules/socket.io-client/node_modules/component-emitter/
extracting: node_modules/socket.io-client/node_modules/component-emitter/History.md
extracting: node_modules/socket.io-client/node_modules/component-emitter/index.js
extracting: node_modules/socket.io-client/node_modules/component-emitter/LICENSE
extracting: node_modules/socket.io-client/node_modules/component-emitter/package.json
extracting: node_modules/socket.io-client/node_modules/component-emitter/Readme.md
extracting: node_modules/socket.io-client/package.json
extracting: node_modules/socket.io-client/README.md
extracting: node_modules/socket.io-client/socket.io.js
creating directory: node_modules/socket.io-parser/
extracting: node_modules/socket.io-parser/.npmignore
extracting: node_modules/socket.io-parser/.travis.yml
extracting: node_modules/socket.io-parser/.zuul.yml
creating directory: node_modules/socket.io-parser/bench/
extracting: node_modules/socket.io-parser/bench/bench.js
extracting: node_modules/socket.io-parser/bench/index.js
extracting: node_modules/socket.io-parser/binary.js
extracting: node_modules/socket.io-parser/History.md
extracting: node_modules/socket.io-parser/index.js
extracting: node_modules/socket.io-parser/is-buffer.js
extracting: node_modules/socket.io-parser/LICENSE
extracting: node_modules/socket.io-parser/Makefile
creating directory: node_modules/socket.io-parser/node_modules/
creating directory: node_modules/socket.io-parser/node_modules/json3/
creating directory: node_modules/socket.io-parser/node_modules/json3/lib/
extracting: node_modules/socket.io-parser/node_modules/json3/lib/json3.js
extracting: node_modules/socket.io-parser/node_modules/json3/lib/json3.min.js
extracting: node_modules/socket.io-parser/node_modules/json3/LICENSE
extracting: node_modules/socket.io-parser/node_modules/json3/package.json
extracting: node_modules/socket.io-parser/node_modules/json3/README.md
extracting: node_modules/socket.io-parser/package.json
extracting: node_modules/socket.io-parser/Readme.md
creating directory: node_modules/to-array/
extracting: node_modules/to-array/.npmignore
extracting: node_modules/to-array/index.js
extracting: node_modules/to-array/LICENCE
extracting: node_modules/to-array/package.json
extracting: node_modules/to-array/README.md
creating directory: node_modules/utf8/
extracting: node_modules/utf8/.gitattributes
extracting: node_modules/utf8/.npmignore
extracting: node_modules/utf8/.travis.yml
extracting: node_modules/utf8/bower.json
extracting: node_modules/utf8/component.json
extracting: node_modules/utf8/Gruntfile.js
extracting: node_modules/utf8/LICENSE-MIT.txt
extracting: node_modules/utf8/package.json
extracting: node_modules/utf8/README.md
creating directory: node_modules/utf8/tests/
extracting: node_modules/utf8/tests/generate-test-data.py
extracting: node_modules/utf8/tests/index.html
extracting: node_modules/utf8/tests/tests.js
extracting: node_modules/utf8/utf8.js
creating directory: node_modules/v-conf/
extracting: node_modules/v-conf/.npmignore
extracting: node_modules/v-conf/configTest.js
extracting: node_modules/v-conf/index.js
creating directory: node_modules/v-conf/node_modules/
creating directory: node_modules/v-conf/node_modules/fs-extra/
extracting: node_modules/v-conf/node_modules/fs-extra/.npmignore
extracting: node_modules/v-conf/node_modules/fs-extra/CHANGELOG.md
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/copy/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy/copy.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy/index.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy/ncp.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/copy-sync/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy-sync/copy-sync.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/copy-sync/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/empty/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/empty/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/ensure/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/file.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/index.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/link.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/symlink-paths.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/symlink-type.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/ensure/symlink.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/json/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/json/index.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/json/output-json-sync.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/json/output-json.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/mkdirs/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/mkdirs/index.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/mkdirs/mkdirs.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/move/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/move/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/output/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/output/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/remove/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/remove/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/streams/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/streams/create-output-stream.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/streams/index.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/util/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/util/assign.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/util/utimes.js
creating directory: node_modules/v-conf/node_modules/fs-extra/lib/walk/
extracting: node_modules/v-conf/node_modules/fs-extra/lib/walk/index.js
extracting: node_modules/v-conf/node_modules/fs-extra/lib/walk/walker.js
extracting: node_modules/v-conf/node_modules/fs-extra/LICENSE
extracting: node_modules/v-conf/node_modules/fs-extra/package.json
extracting: node_modules/v-conf/node_modules/fs-extra/README.md
extracting: node_modules/v-conf/package.json
extracting: node_modules/v-conf/README.md
extracting: node_modules/v-conf/testConfig.json
creating directory: node_modules/wrappy/
extracting: node_modules/wrappy/LICENSE
extracting: node_modules/wrappy/package.json
extracting: node_modules/wrappy/README.md
extracting: node_modules/wrappy/wrappy.js
creating directory: node_modules/xmlhttprequest-ssl/
extracting: node_modules/xmlhttprequest-ssl/autotest.watchr
creating directory: node_modules/xmlhttprequest-ssl/example/
extracting: node_modules/xmlhttprequest-ssl/example/demo.js
creating directory: node_modules/xmlhttprequest-ssl/lib/
extracting: node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
extracting: node_modules/xmlhttprequest-ssl/LICENSE
extracting: node_modules/xmlhttprequest-ssl/package.json
extracting: node_modules/xmlhttprequest-ssl/README.md
creating directory: node_modules/xmlhttprequest-ssl/tests/
extracting: node_modules/xmlhttprequest-ssl/tests/test-constants.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-events.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-exceptions.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-headers.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-redirect-302.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-redirect-303.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-redirect-307.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-request-methods.js
extracting: node_modules/xmlhttprequest-ssl/tests/test-request-protocols.js
extracting: node_modules/xmlhttprequest-ssl/tests/testdata.txt
creating directory: node_modules/yeast/
extracting: node_modules/yeast/index.js
extracting: node_modules/yeast/LICENSE
extracting: node_modules/yeast/package.json
extracting: node_modules/yeast/README.md
creating directory: options/
extracting: options/bit_depths.json
extracting: options/codecs.json
extracting: options/kbps_spotify.json
extracting: options/sample_rates.json
extracting: options/spotify_implementations.json
creating directory: templates/
extracting: templates/asound.snapcast
extracting: templates/mpd_switch_to_fifo.template
extracting: config.json
extracting: index.js
Installing plugin...

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error
```

**Comment by Saiyato** [comment]
Can you try running an extra SSH session and tail the journal? It seems like something's going wrong when installing dependencies. I.e. execute the install.sh, in order to troubleshoot I need to know why it fails on your setup. The script starts with and apt-get update, so that should show at the very least.

Can you step-by-step me through your process?

1. What hardware is used exactly? Any HAT attached?
2. What version of the image are you using?
3. Which actions have you performed prior to installation of the plugin? I.e. which plugins or packages are installed, have you enabled debug mode etc. etc.
4. Can you perform the following command?
`
echo $(curl -s https://api.github.com/repos/badaix/snapcast/releases/latest | grep 'armhf' | cut -d\" -f4)
`
What does it echo?

The rest of the install script is pretty simple and straight forward, I can't image it fails beyond that point.

**Comment by Saiyato** [comment]
Hmmm... one of the first steps is 'a lot' of Progress 70 notifications when updating packages lists. Can you try to sudo apt-get update first?

**Comment by sirtobey** [comment]
I tried `sudo apt update && sudo apt upgrade` before running the script. It still fails.

1. The hardware I use is a Raspberry Pi 2 and Raspberry Pi 3, both in the B version. I don't have a hat installed, as I wanted to test Multiroom audio before committing.

2. I was using the latest version before v2.378, so now I upgraded to v2.378. I had those issues when the previous version was the latest.

3. I haven't changed any settings except enable SSH mode. I have installed no plugins. I went straight from first-time booting the image to installing after running the setup wizzard.

4. 
```
volumio@VolumioBuero:~$ echo $(curl -s https://api.github.com/repos/badaix/snapcast/releases/latest | grep 'armhf' | cut -d\" -f4)
snapclient_0.13.0_armhf.deb https://github.com/badaix/snapcast/releases/download/v0.13.0/snapclient_0.13.0_armhf.deb snapserver_0.13.0_armhf.deb https://github.com/badaix/snapcast/releases/download/v0.13.0/snapserver_0.13.0_armhf.deb
```


This is the journal output:
```
volumio@VolumioBuero:~$ sudo journalctl -f
-- Logs begin at Sun 2018-02-18 14:42:52 UTC. --
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Scanning into folder /data/plug                                     ins/
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Scanning category miscellanea
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Plugin snapcast found in folder                                      but missing in configuration. Removing folder.
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Plugin folders cleanup complete                                     d
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Error: Error
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Folder /tmp/plugins removed
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Folder /tmp/downloaded_plugin.z                                     ip removed
Mar 13 23:20:43 VolumioBuero volumio[869]: info: Folder /data/temp removed
Mar 13 23:21:58 VolumioBuero sudo[17749]: volumio : TTY=pts/2 ; PWD=/home/volumi                                     o ; USER=root ; COMMAND=/bin/journalctl -f
Mar 13 23:21:58 VolumioBuero sudo[17749]: pam_unix(sudo:session): session opened                                      for user root by volumio(uid=0)
Mar 13 23:22:13 VolumioBuero volumio[869]: info: Downloading plugin at http://12                                     7.0.0.1:3000/plugin-serve/snapcast.zip
Mar 13 23:22:13 VolumioBuero volumio[869]: info: END DOWNLOAD: http://127.0.0.1:                                     3000/plugin-serve/snapcast.zip
Mar 13 23:22:13 VolumioBuero volumio[869]: info: Folder /tmp/plugins removed
Mar 13 23:22:14 VolumioBuero volumio[869]: info: Checking if plugin already exis                                     ts
Mar 13 23:22:14 VolumioBuero volumio[869]: info: Rename folder
Mar 13 23:22:14 VolumioBuero volumio[869]: info: Folder /tmp/downloaded_plugin.z                                     ip removed
Mar 13 23:22:14 VolumioBuero volumio[869]: info: Move to category
Mar 13 23:22:15 VolumioBuero volumio[869]: info: Checking if install.sh is prese                                     nt
Mar 13 23:22:15 VolumioBuero volumio[869]: info: Executing install.sh
Mar 13 23:22:15 VolumioBuero sudo[17893]: pam_unix(sudo:auth): authentication fa                                     ilure; logname= uid=1000 euid=0 tty= ruser=volumio rhost=  user=volumio
Mar 13 23:22:17 VolumioBuero sudo[17893]: pam_unix(sudo:auth): conversation fail                                     ed
Mar 13 23:22:17 VolumioBuero sudo[17893]: pam_unix(sudo:auth): auth could not id                                     entify password for [volumio]
Mar 13 23:22:17 VolumioBuero sudo[17893]: volumio : 1 incorrect password attempt                                      ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins/miscellanea/s                                     napcast/install.sh
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Install script return the error                                      Error: Command failed: echo volumio | sudo -S sh /data/plugins/miscellanea/snap                                     cast/install.sh > /tmp/installog
Mar 13 23:22:17 VolumioBuero volumio[869]: [sudo] password for volumio: Sorry, t                                     ry again.
Mar 13 23:22:17 VolumioBuero volumio[869]: [sudo] password for volumio:
Mar 13 23:22:17 VolumioBuero volumio[869]: sudo: 1 incorrect password attempt
Mar 13 23:22:17 VolumioBuero volumio[869]: info: An error occurred installing th                                     e plugin. Rolling back config
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Plugin folders cleanup
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning into folder /volumio/a                                     pp/plugins/
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category audio_interfa                                     ce
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category miscellanea
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category music_service
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category plugins.json
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category system_contro                                     ller
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category user_interfac                                     e
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning into folder /data/plug                                     ins/
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Scanning category miscellanea
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Plugin snapcast found in folder                                      but missing in configuration. Removing folder.
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Plugin folders cleanup complete                                     d
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Error: Error
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Folder /tmp/plugins removed
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Folder /tmp/downloaded_plugin.z                                     ip removed
Mar 13 23:22:17 VolumioBuero volumio[869]: info: Folder /data/temp removed
```

Seems to me the trouble is here:
```
Mar 13 23:32:00 volumiobuero sudo[1430]: pam_unix(sudo:auth): authentication fai                      lure; logname= uid=1000 euid=0 tty= ruser=volumio rhost=  user=volumio
Mar 13 23:32:02 volumiobuero sudo[1430]: pam_unix(sudo:auth): conversation faile                      d
Mar 13 23:32:02 volumiobuero sudo[1430]: pam_unix(sudo:auth): auth could not ide                      ntify password for [volumio]
Mar 13 23:32:02 volumiobuero sudo[1430]: volumio : 1 incorrect password attempt                       ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins/miscellanea/sn                      apcast/install.sh
```

**Comment by sirtobey** [comment]
I forgot to mention this (but it might be relevant considering the journal sudo error): I did also change the password of the volumio user on both systems..

**Comment by Saiyato** [comment]
That would pose a problem once installed, can you try it without changing the password please?
The install script does not need a password, but the plugin does.

Just to be sure, can you try the whole sequence before changing the password and then change it afterwards?

**Comment by sirtobey** [comment]
It worked now! Damn, I'm sorry, I really forgot that I changed the password and didn't think it would matter.

Now, can I change the password after installation of the plugin? Or will I run into problems every time I update it?

Is this perhaps something we could fix? I am not familiar with plugin development for volumio, but maybe I could assist you with this.. Because I really don't feel comfortable running several raspberries in my network with default passwords with root access :)

**Comment by Saiyato** [comment]
Good point, we can look into the incorporation of more security... however, installing the plugin uses Volumio's code, not mine ;)

I can solve the problem that occur after. Which is why I will create a new issue for that
